### ISSUE TITLE
Failing test in Behaviors

### ISSUE THREAD

**Issue by agent-q1** [Terasology/Behaviors#43]
### Failing test `TestActions` in Behaviors
 
When trying to run `TestActions` in the test directory of the Behaviors module, I ran into some Null Pointer Exceptions that caused the tests to fail. The error is in this line 

`List<BehaviorNodeComponent> list = categoryComponents.get(component.category);`

### Why it happens (maybe)

This happens because `component` here is null. Thus the underlying cause of the error seems to be the AssetManager not being able to load the prefab assets. (The other assets, however, seem to be loaded).

### Failure to load prefabs

This is probably an issue with the `HeadlessEnvironment` itself. This is the line that references the constructor to the PojoPrefab class 

`assetTypeManager.registerCoreAssetType(Prefab.class,
                PojoPrefab::new, false, "prefabs");`

However, the constructor of the `PojoPrefab` class (which is responsible for registering the assets ) is not being called for some reason. It should also be noted that the constructors of other assets such as `BlockShapeImpl` are called.

**Comment by jdrueckert** [comment]
The test in question was removed in https://github.com/Terasology/Behaviors/pull/73 due to the SUT being unclear and it seemingly testing multiple things at once.
